# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

www.timezero.ru	FALSE	/	FALSE	0	tzl	Terminal Police
www.timezero.ru	FALSE	/	FALSE	0	tzses	14594707640432912245
www.timezero.ru	FALSE	/	FALSE	0	tzsrv	city1.timezero.ru
www.timezero.ru	FALSE	/	FALSE	0	tzlang	ru
